# GPCI
GPCI_DATA_DIRECTORY = "gpci_data"
GPCI_DATA_FILE_EXTENSION = "csv"

# NUMBEO
NUMBEO_DATA_DIRECTORY = "numbeo_data"
NUMBEO_DATA_FILE_EXTENSION = "json"

# COMMON
DATAFRAME_FILE_NAME = "dataframe"
PICKLE_FILE_EXTENSION = "p"
